version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/xpangzeng/Desktop/dockerVolumn/mysql
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/xpangzeng/Desktop/dockerVolumn/redis
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
