version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: 'always'
    depends_on:
      - mysql-container3
      - redis-container3
    ports:
      - '30086:30086'
    networks:
      - common-network3
    dns: 114.114.114.114
  mysql-container3:
    image: mysql
    volumes:
      - /Users/zengxpang/mysql2:/var/lib/mysql
    networks:
      - common-network3
  redis-container3:
    image: redis
    volumes:
      - /Users/zengxpang/redis:/data
    networks:
      - common-network3
networks:
  common-network3:
    driver: bridge
