version: '3.8'
services:
  nest-app:
    container_name: nest-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: 'on-failure'
    env_file:
      - ./src/.env
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '30086:30086'
    networks:
      - common-network

  mysql-container:
    container_name: mysql-container
    image: mysql
    restart: 'on-failure'
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: zengxpang
      MYSQL_PASSWORD: zengxpang
      MYSQL_DATABASE: meeting_room
      MYSQL_USER: zxp
      MYSQL_ROOT_HOST: '%'
    volumes:
      - "./deploy/mysql/db:/var/lib/mysql"
      - "./deploy/mysql/conf/my.cnf:/etc/mysql/conf.d"
      - "./deploy/mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - common-network

  redis-container:
    image: redis
    container_name: redis-container
    restart: 'on-failure'
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - "./deploy/redis/db:/data"
      - "./deploy/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./deploy/redis/logs:/logs"
    networks:
      - common-network

networks:
  common-network:
    name: common-network
    driver: bridge
